### ISSUE TITLE
Deleting the space from a <key [space v] pressed?> causes a crash

### ISSUE THREAD

**Issue by wizzwizz4** [PolyEdge/ScratchEdit#37]
This is probably in the horrible part of the code. Traceback:

```Traceback (most recent call last):
  File "\\cgs-svr-vmusers\14smould$\OnSystem\ScratchEdit.py", line 840, in regenerate_lb
    raise TypeError()
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\cgs-svr-vmusers\14smould$\OnSystem\ScratchEdit.py", line 842, in regenerate_lb
    raise TypeError()
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\cgs-svr-vmusers\14smould$\OnSystem\ScratchEdit.py", line 854, in regenerate_lb
    name = _(x).format(*(ls[m] for m in range(1, param_count + 1)))
  File "\\cgs-svr-vmusers\14smould$\OnSystem\ScratchEdit.py", line 854, in <genexpr>
    name = _(x).format(*(ls[m] for m in range(1, param_count + 1)))
IndexError: list index out of range
```

**Comment by wizzwizz4** [comment]
The problem here is that ScratchEdit tried to make the `<key [space v] pressed?>` text, and it failed. The solution would be to add some kind of error condition.
